"""empty message

Revision ID: 0a05bd487880
Revises: 
Create Date: 2022-01-19 19:32:21.076598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a05bd487880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desconto', sa.String(length=15), nullable=False),
    sa.Column('código', sa.String(length=20), nullable=False),
    sa.Column('forma_utilizacao', sa.String(length=100), nullable=False),
    sa.Column('campanha', sa.String(length=20), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_termino', sa.DateTime(), nullable=True),
    sa.Column('limite_usuarios', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('código')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha', sa.String(length=40), nullable=False),
    sa.Column('endereco', sa.String(length=80), nullable=False),
    sa.Column('cidade', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cep', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cupom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupom.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo_entrega', sa.String(length=15), nullable=False),
    sa.Column('preco_entrega', sa.String(length=15), nullable=False),
    sa.Column('quantidade_itens', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Float(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=15), nullable=False),
    sa.Column('pagamento_confirmado', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id_cupom', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cupom'], ['cupom.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=25), nullable=False),
    sa.Column('cor', sa.String(length=15), nullable=False),
    sa.Column('quilometragem', sa.Float(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('preco_normal', sa.Float(), nullable=False),
    sa.Column('preco_descontado', sa.Float(), nullable=True),
    sa.Column('cambio', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carro_placa'), 'carro', ['placa'], unique=True)
    op.create_table('moto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=25), nullable=False),
    sa.Column('cor', sa.String(length=15), nullable=False),
    sa.Column('quilometragem', sa.Float(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('preco_normal', sa.Float(), nullable=False),
    sa.Column('preco_descontado', sa.Float(), nullable=True),
    sa.Column('cambio', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moto_placa'), 'moto', ['placa'], unique=True)
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo_entrega', sa.String(length=15), nullable=False),
    sa.Column('preco_entrega', sa.String(length=15), nullable=False),
    sa.Column('quantidade_itens', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Float(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id_carro', sa.Integer(), nullable=True),
    sa.Column('id_moto', sa.Integer(), nullable=True),
    sa.Column('id_cupom', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carro'], ['carro.id'], ),
    sa.ForeignKeyConstraint(['id_cupom'], ['cupom.id'], ),
    sa.ForeignKeyConstraint(['id_moto'], ['moto.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrinho')
    op.drop_index(op.f('ix_moto_placa'), table_name='moto')
    op.drop_table('moto')
    op.drop_index(op.f('ix_carro_placa'), table_name='carro')
    op.drop_table('carro')
    op.drop_table('pedido')
    op.drop_table('association')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('cupom')
    # ### end Alembic commands ###
